### ISSUE TITLE
데이터 수집방법

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#1]
데이터 수집을 꽃 이름과 꽃말을 CSV파일로 저장하는 방법으로 
DB를 이미 만들었는데 만들고 나니까 
농촌진흥청 국립원예특작과학원_오늘의 꽃 조회 서비스(2.0)라고 Open api가 있는데
어떤 것을 사용하는 것이 나을까요?
제 개인적인 의견으로는 꽃 이름과 꽃말만 사용한다면 csv파일 그래로 하는게 나을 거같고
다른 것도 활용한다면 이 open api를 활용하는 것이 좋을 것 같습니다.
open api를 사용하면 확장성이 좋겠지만 다시 사용방법을 익혀야하는 문제점도 있을 거같아서요.
물론, csv파일 외의 정보를 활용해야한다면 open api를 활용하겠죠.

링크 걸어둡니다.
https://www.data.go.kr/data/15084605/openapi.do
@hdgys45 @gfdsa8

**Comment by hdgys45** [comment]
완성도가 높아질 수 있다면 Open api를 활용하는 것이 좋다 생각합니다.

**Comment by gfdsa8** [comment]
추가할 내용이 생기면 유동성 있게 변경하기 쉽도록 open api 활용하는 것이 좋을 것 같습니다.

**Comment by hdgys45** [comment]
그렇다면 현재는 CSV파일을 데이터파일로 진행해도 된다는 의미를 받아들이겠습니다!

**Comment by ehdcjf4874** [comment]
음 그럼 일단 CSV파일로 해보고 추가할 내용이 있으면 OPEN API를 사용하는걸로 결정해도 될까요?



> 완성도가 높아질 수 있다면 Open api를 활용하는 것이 좋다 생각합니다.

이 말도 결국 더 많은 기능이 필요할때에 OPEN API를 써야 완성도가 높아지는 것이니까요.
@hdgys45 @gfdsa8

**Comment by ehdcjf4874** [comment]
더 하실 말씀 없으면 이슈 내일중으로 닫겠습니다.
