### ISSUE TITLE
요구사항 분석서

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#10]
요구사항 분석서 관련해서 
수정된 사항 올립니다.

2.2 기능 분류 및 설명 수정
추천기능 추가

3.2 동적 분석 수정
사용자는 본인이 원하는 상황별 혹은, 특정 단어와 ~
-> 사용자는 본인이 원하는 특정 단어와 ~ 로 수정
[고찰팀_요구사항분석서.zip](https://github.com/hdgys45/Flower-Recommendation-System/files/7320967/_.zip)
@hdgys45  @gfdsa8

**Comment by hdgys45** [comment]
확인했습니다

**Comment by ehdcjf4874** [comment]
모두 숙지했으면 닫겠습니다.
