### ISSUE TITLE
10월 12일 발표 피드백

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#11]
10월 12일 성능평가요소에 대한 발표를 하고 
교수님께 피드백을 받았습니다.
피드백을 토대로 정리한 내용을 ppt로 올리겠습니다.
추가하거나 수정할 내용이 있으면 다시 올려주세요.
[고찰팀 6주차 Project Proposal (2).pptx](https://github.com/hdgys45/Flower-Recommendation-System/files/7326337/6.Project.Proposal.2.pptx)

@hdgys45  @gfdsa8

**Comment by gfdsa8** [comment]
확인했습니다. 저는 PPT 내용 뿐만 아니라 추가할게 더 있다고 생각합니다.
저희 데이터베이스의 기초가 되는 "농촌진흥청의 꽃말 사전" 과 저희 꽃 추천 시스템을 비교하는 것입니다.
구글에 검색해본 결과 꽃 추천하는 페이지는 없는 것 같으며, 이미 기존에 있던 꽃 검색 사이트인 "농촌진흥청의 꽃말 사전"과의 비교를 통하면, 저희 시스템의 차별성이 더욱 강조될 것으로 생각됩니다.

비교 방법은 저희 웹페이지 밑에서 별점을 받을 수 있는데, 별점의 기준을 "농촌진흥청의 꽃말 사전과 비교했을 때 얼마나 좋은가? "에 대한 것으로 바꾸고, 별점을 받을 때 "농촌진흥청의 꽃말 사전"의 URL도 같이 넣어서 비교하거나 아니면 별점 받는 페이지 내에 "농촌진흥청의 꽃말 사전"의 사진을 넣어서 비교할 수 있도록 하면 될 것 같습니다.

**Comment by ehdcjf4874** [comment]
확인했습니다. 닫도록하겠습니다.
