### ISSUE TITLE
10월 18일(월) 멘토링 이슈

### ISSUE THREAD

**Issue by hdgys45** [hdgys45/Flower-Recommendation-System#12]
10월 18일에 하는 멘토링 주제를 정하고자 합니다. 의견있으시면 말씀해주세요.

@ehdcjf4874 @gfdsa8

**Comment by ehdcjf4874** [comment]
프로젝트의 주제를 통일하는 것이 나은지 주제를 벗어나더라도 기능이  추가되는것이 나은지에 대해서

**Comment by gfdsa8** [comment]
제가 생각하기에 가장 중요한 주제는 개발환경인 것 같습니다.
저 같은 경우에는 아직까지 제대로된 웹이나 안드로이드 어플을 개발해 본 적이 없기 때문에 둘 중 어느 것이 저희 프로젝트에 맞는 것인지 잘 모릅니다. 그렇기에 교수님의 의견을 들어보면서 이번에 저희 프로젝트의 진로를 결정해야 한다고 생각합니다.
