### ISSUE TITLE
의미별 꽃추천할때 의미선정

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#14]
의미별 꽃추천할때 모든 꽃말의 의미를 다 쓰기에는 무리가 있는 것같아서 의미선정 기준이 필요합니다!
다양하고 많은 꽃말이 있어서 의미선정을 어떻게 할 지 토의를 해야할거같습니다.

@hdgys45 @gfdsa8

**Comment by hdgys45** [comment]
저희 데이터베이스에서 빈도 수가 높은 순서대로 몇개 선택하면 좋을거같습니다.

**Comment by gfdsa8** [comment]
꽃말을 일일이 읽어보면서 비슷한 단어끼리 묶는 것이 좋을 거 같습니다.(예를 들어 사랑과 애정 등을 한번에 묶는 것)
그리고 내부에 같은 단어가 사용되지만 뜻이 부정적인 것과 긍정적인 것이 있을 수 있는데 (예를 들어 긍정적-참사랑 / 부정적-사랑의 절망)등도 분류 하면 될 것 같습니다. -> 이렇게 긍정적인 단어와 부정적인 단어가 같이 있는 단어를 검색하는 경우, 긍정적인 단어 또는 부정적인 단어를 고를 수 있도록 하는 것도 좋아 보입니다.

**Comment by ehdcjf4874** [comment]
의견 반영하도록 하겠습니다. 
이슈 닫겠습니다.
