### ISSUE TITLE
php와 아파치 연동 시 불편사항

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#18]
php와 아파치 연동시
아파치의 htdocs파일으로 모든 파일을 옮겨서 설정해야 
php가 작동합니다.
그럴경우 현재 작업중인 파일을 git으로 올릴때 수정사항이 반영되지 않습니다.
해결방안을 알고 계신 분은 말씀해주세요
@hdgys45 @gfdsa8

**Comment by gfdsa8** [comment]
작업 PC에서 만들고 있는 대부분의 작업물은 htdocs 파일안에 있을 것이니
htdocs 파일 자체를 올리는 건 어떨까요? 그러면 좀 더 편하게 올릴 수 있다고 생각합니다.

**Comment by ehdcjf4874** [comment]
현재 작업중인 git폴더안에서 못하는게 아쉽지만 그렇게라도 해야겠네요. 
감사합니다.

**Comment by ehdcjf4874** [comment]
해결했으므로 이슈 닫겠습니다

**Comment by ehdcjf4874** [comment]
해결했으므로 이슈닫겠습니다
