### ISSUE TITLE
php파일 생성 및 관리 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#19]
의미별 꽃말 추천기능에서
php파일을 여러개 만들어서 index.html에서 링크로 가져와도 괜찮을까요? 
이런 의문이 드는 이유가 여러개의 php파일이 하나의 html파일에 링크로 연동이 될 수 있는록 아파치에서 지원하는지 궁금하기 떄문입니다.
ex> 사랑.php, 슬픔.php...
@hdgys45 @gfdsa8

**Comment by gfdsa8** [comment]
html의 <a>태그를 사용하면 충분히 된다고 생각합니다.
따라서 각각에 맞는 php파일을 만들어서 <a> 태그를 사용해서 링크를 달아주면 됩니다.
