### ISSUE TITLE
README.md 파일수정

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#2]
README.md 파일은 사용자가 어떻게 써줬으면 하는 것을 명시하는 파일입니다.
저는 이전에 이것을 프로젝트를 소개하는 파일이라고 생각하고 우리의 PPT를 참고해서  README.md파일을 만들어서
README.md파일에 부합하다고 생각합니다. 
필요한 것은 그대로 쓸 수도 있으니까 만들어 놓은것은 남기겠습니다. 
개인적으로 소개하는 부분은 남겨놓는 것이 좋다고 생각합니다.
어떻게 쓸 것인지 토의가 필요합니다!
@hdgys45 @gfdsa8

**Comment by bytecell** [comment]
Prof: 논의를 하고자 하는 대상을 명시하고 싶다면, @ 를 사용해서 글을 작성하면,
상대방에게 알림메일이 가게 되니 참고해주세요.

**Comment by hdgys45** [comment]
소개하는 부분을 남기는건 저도 동의합니다.
필요한 내용들은 PPT를 참고하지 않고 작성하는 것이 좋을거 깉습니다.

**Comment by hdgys45** [comment]
> 소개하는 부분을 남기는건 저도 동의합니다.
> 필요한 내용들은 PPT를 참고하지 않고 작성하는 것이 좋을거 같습니다.

**Comment by ehdcjf4874** [comment]
README.MD파일은 누구나 수정할 수 있습니다.
수정이 필요하거나 사용자에게 필요하다고 생각되는 안내는 추가해주세요!

**Comment by gfdsa8** [comment]
README.MD에서 띄어쓰기와 오탈자 수정 및 추가 내용 넣었습니다.

**Comment by ehdcjf4874** [comment]
> README.MD에서 띄어쓰기와 오탈자 수정 및 추가 내용 넣었습니다.

commit 할 때 Update Readme.md File로 되어 있으면 
추가 commit 할 때 update_2 Readme.md file 이렇게 몇번째 수정인지 넣어줬으면 좋겠습니다.
@hdgys45 @gfdsa8

**Comment by ehdcjf4874** [comment]
readme.md에 이미지 삽입할 때, 파일이름에 띄어쓰기가 있으면 정상적으로 삽입이 안됩니다.
띄어쓰기 없이 파일이름을 작성해야합니다.
ex>8주차 순서도.png -> 8주차_순서도.png로 바꿔주어야 합니다.
@hdgys45 @gfdsa8

**Comment by ehdcjf4874** [comment]
이상 없으면 닫겠습니다!
