### ISSUE TITLE
index.html관련 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#20]
index.html에 파일에 php 코드를 포함시키려면
index.php파일로 바꿔야합니다.
이때, php파일로 바꾸면 html코드가 정상적으로 실행되지 않고 코드로만 나오게 됩니다.
이러면 html파일을 php파일로 확장명을 바꿔야 할까요? 
그리고 이제는 꼭 아파치 서버가 구동중이여만 실행이 되는건가요?

**Comment by gfdsa8** [comment]
굳이 index.php로 안 바꿔도 될 것 같습니다.
제가 해본 결과 index.html에 <a>태그로 php 위치로 연동 시키는 것이 가능합니다.
하지만 이때 아파치는 꼭 켜져 있는 상태여야만 하고, 아파치 파일 중 "htdocs"라는 곳에 php파일은 물론 html 만들 때 사용하던 파일들도 넣어야 정상 작동합니다.

**Comment by ehdcjf4874** [comment]
네. 감사합니다
그렇게 하니까 실행됩니다!
