### ISSUE TITLE
상황별 추천기능 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#21]
상황별 추천기능에
송별회에서는 '%슬픔%'와 같이 어떤 감정이 있는지 넣으려고 하는데
또 다른 감정은 무엇이 있을까요?
또 송별회말고도 결혼식,졸업식,장례식에는 어떻게 넣어야 할 지 의견 부탁드립니다.
@hdgys45 @gfdsa8

**Comment by gfdsa8** [comment]
flower_db.csv 파일에서 꽃말을 보며 찾아본 결과

꽃말 기준으로

송별회에는
[추억, 친밀, 불후, 불변, 헤어진 벗에게 보내는 마음, 그리움, 슬픔, 이별]

결혼식에는
[사랑, 관심, 축복, 정열, 기쁜 소식, 행운, 행복, 환희, 희망, 기쁨, 찬사, 결혼, 좋은 소식]

졸업식에는
[도전, 환호, 독립, 용기, 상쾌한 기분, 미래를 즐긴다]

장례식에는
[고독, 쓸쓸함, 불후, 불변, 다시 만납시다, 당신을 버리지 않음, 침묵, 허무한 삶, 헤어진 벗에게 보내는 마음, 기다리는 마음, 슬픔, 이별, 애석, 편히 쉬세요, 당신 곁에 있겠습니다.]
또한 서양에서는 백합을 장례식에 사용하기 때문에 따로 넣는 것도 나쁘지 않을 것 같습니다. (참고로 백합의 꽃말은 순결인데 같은 꽃말을 가진 꽃도 있으므로 순결이라는 꽃말을 쓸 수는 없을 것 같습니다.)

이 정도가 있을 것 같습니다. 단어와 같이 딱 떨어지는 것이 있는 반면에 문장처럼 되어 있는 꽃말도 있습니다. 이는 SELECT문을 사용할 때, 예외로 넣어야 할 것 같습니다.

**Comment by ehdcjf4874** [comment]
이렇게 수정하면 이전보다 훨씬 좋을것같습니다.
이대로 수정 후 commit 가능할까요?
@gfdsa8

**Comment by ehdcjf4874** [comment]
완료되었으므로 닫겠습니다
