### ISSUE TITLE
순서도 수정 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#22]
readme.md파일에 순서도 수정이 필요해보입니다.
받는 사람입력 -> 대상별 카테고리 클릭
상황별 입력 -> 상황별 카테고리 클릭
의미별 카테고리 클릭 추가 
@gfdsa8

**Comment by gfdsa8** [comment]
feature_connect branch에 있는 readme.md 파일 수정하여 설치법까지 넣었습니다.
나중에 merge 할 때 확인해보시면 될 것 같습니다.

**Comment by ehdcjf4874** [comment]
확인했습니다. 이슈 닫겠습니다
