### ISSUE TITLE
merge이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#27]
![image](https://user-images.githubusercontent.com/62986349/145679963-3d41f964-ad23-4d32-9ad4-249280fd1d36.png)
여기서 1단계, 2단계를 어떻게 해야하나요?

**Comment by gfdsa8** [comment]
저희는 따로따로 작업을 진행하지 않고 카톡을 통하여 협의 하에 마스터 branch에 넣기 때문에 각자 처음 가지고 왔던 마스터 branch가 다르지 않습니다.
따라서 1단계는 저희와는 해당사항이 없을 것 같습니다.
2단계는 자신이 만든 Feature branch를 다른 팀원이 merge를 해야한다는 것 같습니다.

**Comment by hdgys45** [comment]
처음부터 시작을  Feature Branch를 생성한후 Master에 옮겼으니 해당하지 않을것 같습니다.

**Comment by ehdcjf4874** [comment]
이슈 닫겠습니다
