### ISSUE TITLE
검색.php 결과출력화면 이슈1

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#28]
검색 화면 출력시 header부분에 
검색 시 모두 동일하게 검색어 라고 뜨는데
이것을 php로 받아와서 검색한 결과로 출력되게하는게 어떨까요?
ex> 검색어: 카네이션
검색 결과: 현재 카네이션을 보고있습니다.

**Comment by gfdsa8** [comment]
좋은 방법인 것 같습니다.
저도 처음에 그 방법을 고민하다가 안될 것 같아서 "검색어"라고 통일 했던 겁니다.

**Comment by hdgys45** [comment]
네 동의합니다.

**Comment by ehdcjf4874** [comment]
이슈 닫겠습니다
