### ISSUE TITLE
검색.php 결과출력화면 이슈2

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#29]
검색 php의 결과출력화면에서
꽃말부분이 길어서 글이 짤리는 현상이 생기는데 어떻게 수정하면 좋을까요?

**Comment by gfdsa8** [comment]
저 같은 경우는 안 짤리지만, 짤린다면 글자 크기를 살짝 줄이는 것이 좋을 것 같습니다.

**Comment by hdgys45** [comment]
검색.php 결과출력화면 이슈2에 대한 답변으로 h3태그의 스타일을 width:1000px로 하면됩니다.

**Comment by ehdcjf4874** [comment]
이슈 닫겠습니다
