### ISSUE TITLE
jquery.poptrox.min.js작동 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#31]
jquery.poptrox.min.js가 정상적으로 작동하지 않습니다.
왜 그런지 아시는분 답변부탁드립니다.

**Comment by gfdsa8** [comment]
php 파일에서는 불러오지 못하는 것 같습니다.
예를 들어 "결혼식.php" 파일에서 jquery.poptrox.min.js라는 javascript를 불러오려고 하면 불러오지 못하지만
"결혼식.html"로 확장자를 바꾸니 작동은 하지만 데이터베이스와의 연동이 끊깁니다.

**Comment by ehdcjf4874** [comment]
이슈 닫겠습니다
