### ISSUE TITLE
꽃정보와 꽃사진의 불일치 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#32]
결혼식.php 파일 실행시  꽃정보와 꽃사진이 불일치합니다.
다른 파일들도 불일치하는 것으로 보입니다.
수정바랍니다.
@gfdsa8

**Comment by gfdsa8** [comment]
제가 feature_connect에서는 고쳤지만 아직 배포를 안한 flower_db.csv 파일 때문인 듯 합니다.
왜냐하면, 처음 flower_db.csv 파일은 "ORDER BY 월일 ASC"가 정상적으로 작동하지 않았습니다.
예를 들어 10월 -> 1월 -> 11월 순으로 되었지만 10미만의 월과 일 앞에 '0'을 붙여서 그런 문제를 해결하였고,
1월부터 순서대로 보여주기 위하여 "결혼식.php"에도 "ORDER BY 월일 ASC"가 들어가 있어서 생긴 것입니다.

feature_connect 에 있는 flower_db.csv 파일을 받으시면 괜찮을 겁니다.

**Comment by ehdcjf4874** [comment]
이슈 닫겠습니다
