### ISSUE TITLE
$row = mysqli_fetch_array($result) 코드 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#36]
$row = mysqli_fetch_array($result)가 무엇을 의미하는지 아시는분 답변 부탁드립니다.

**Comment by gfdsa8** [comment]
$row = mysqli_fetch_array($result)는 php에서 하나의 행을 가져오는 것 같습니다.
예를 들어 사랑이라는 꽃이 3개 있다고 생각하면 각각 0,1,2의 index를 가진다고 칩시다.
이때, $row = mysqli_fetch_array($result)를 사용하면 index 0을 불러온다는 것입니다.
따라서 index 0을 제외하고 1~2만 출력하고 싶으면
$row = mysqli_fetch_array($result);     // index 0
$row = mysqli_fetch_array($result);     // index 1
echo....
의 형태로 쓰면 됩니다.

**Comment by hdgys45** [comment]
mysqli_fetch_array 함수는 mysqli_query를 통해 얻은 result set에서 레코드를 1개씩 리턴해주는 함수입니다.
