### ISSUE TITLE
footer의 저작권 이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#37]
index.html에 있는 footer에 저작권이 써져있는데
우리가 수정했으므로 우리의 저작권을 써야할지, 그대로 원본의 저작권을 써야할지 의문입니다.
답변 부탁드립니다.

**Comment by gfdsa8** [comment]
제가 봤을 때는 두 개 다 쓰는게 가장 좋을 것 같습니다.

**Comment by hdgys45** [comment]
저희는 영리 목적을 가지고 있는 것이 아니므로 출처를 밝히는 의미에서 같이 쓰는 것이 좋다고 생각합니다.
