### ISSUE TITLE
mysql 데이터베이스 생성이슈

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#38]
mysql 데이터베이스를 github에 추가해야 되는데 
mysql 데이터 저장소 아시는 분있나요?

**Comment by gfdsa8** [comment]
윈도우 환경에서는 기본 데이터 디렉터리가 C:\mysql\data 라고 합니다.

**Comment by hdgys45** [comment]
Windows 환경에서는 기본 데이터 디렉터리가 c:\mysql\data입니다.
