### ISSUE TITLE
요구사항 정의서

### ISSUE THREAD

**Issue by hdgys45** [hdgys45/Flower-Recommendation-System#4]
1. 꽃말을 입력받아 해당하는 꽃들을 출력한다.
2. 입력받은 꽃말과 일치하는 데이터가 데이터베이스 내에 존재하는지 확인한다.
3. 일치하는 데이터가 존재하지 않는다면 오류멘트를 출력한다.
 저희 시스템에 대표적인 요구사항들입니다. 이외에 추가할 내용 및 수정하실 부분있으시다면 말씀해주세요.
@ehdcjf4874 @gfdsa8

**Comment by hdgys45** [comment]
양식을 참고해서 한다면 위 글은 기능적 요구사항과 비기능적 요구사항이 섞인 글 같습니다.
따로 따로 분류해서 적어야 합니다. 
EX> 기능적) 꽃말을 입력받아 해당하는 꽃들을 출력한다.
비 기능적) 입력받은 꽃말과 일치하는 데이터가 데이터베이스 내에 존재하는지 확인한다.

양식을 보고 역할을 배분해서 일단 요구사항 정의서를 만들어야할 것 같습니다.

**Comment by ehdcjf4874** [comment]
양식을 참고해서 한다면 위 글은 기능적 요구사항과 비기능적 요구사항이 섞인 글 같습니다.
따로 따로 분류해서 적어야 합니다.
EX> 기능적) 꽃말을 입력받아 해당하는 꽃들을 출력한다.
비 기능적) 입력받은 꽃말과 일치하는 데이터가 데이터베이스 내에 존재하는지 확인한다.

양식을 보고 역할을 배분해서 일단 요구사항 정의서를 만들어야할 것 같습니다.

**Comment by gfdsa8** [comment]
교수님이 주신 요구사항 분석서 예시에서는
- Use Case Diagram
- Use Case Description
- Class Diagram
- CRC card
- Sequence Diagram
- 요구사항 추적표
등이 있습니다. 이 부분은 위의 양식을 보고 저희 프로젝트에 맞춰서 바꾸면 될 것 같습니다.
