### ISSUE TITLE
데이터베이스의 관리 및 사용환경에 관하여

### ISSUE THREAD

**Issue by hdgys45** [hdgys45/Flower-Recommendation-System#5]
csv파일을 바탕으로 생성된 데이터베이스를 어떻게 사용할 것인지 의견을 듣고 싶습니다.

1. 서버를 구축하여 관리한다.
2. 어플리케이션에 포함하여 오프라인으로도 사용할 수 있게한다.

2번이 1번보다 사용환경의 제약이 적다는 장점이 있습니다. 그러나, 1번에 경우 서버만 업데이트 하면 데이터가 갱신되지만 2번에 경우 어플리케이션을 업데이트 해야된다는 번거로움이 있습니다.

본인의 의견과 건의 및 수정하고 싶은 사항을 알려주세요.

@ehdcjf4874 @gfdsa8

**Comment by gfdsa8** [comment]
2번이 좋다고 생각합니다.
왜냐하면 꽃말의 경우 추가될 가능성이 별로 없어서 데이터 갱신이 크게 중요하지 않다고 생각합니다.
또한 오프라인으로 하는 경우 동시 접속자 수에 제약이 없습니다.

**Comment by ehdcjf4874** [comment]
그렇다면 어플상에서 사용자가 데이터베이스 전체를 볼 수 있게 만든다는 의미로 생각해도되나요?

**Comment by hdgys45** [comment]
그런 기능을 의도한건 아니지만, 추가해도 좋을거 같습니다.
