### ISSUE TITLE
구현방법 결정과 추천시스템 기능 추가에 관하여

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#6]
멘토링 후에 다음주까지 결정해야 되는게 있습니다.

  1. 구현방법 결정: 안드로이드 어플, 웹
  2. 추천시스템 기능 추가 
  ex> 상황별, 기념일별, 받는 사람이 누구인지에 따른 추천

많은 의견 주세요!
@hdgys45  @gfdsa8

**Comment by gfdsa8** [comment]
2번 관련으로 생각한 걸 이야기 해보자면,
자신이 원하는 꽃말을 검색 할 때, 결과로 오늘의 꽃도 추가하는 것은 어떨까요?
예를 들어 9월 29일에 A라는 꽃말을 검색하면, 
1. A라는 꽃말과 관련된 꽃들
2. 9월 29일 오늘의 꽃 [9월 29일 : 수세미 /  꽃말 : 여유]
이런 식으로 하면 추천을 2개 할 수 있습니다.

**Comment by hdgys45** [comment]
국내에서 사용되는 꽃말과 외국에서 사용되는 꽃말이 다른걸로 압니다. 국내외 기준으로 꽃을 보여줘도 좋을거 같습니다.
만약 연령대별로 꽃을 추천한다면 자료 조사를 어떻게 할지 궁금합니다.

@ehdcjf4874 @gfdsa8

**Comment by ehdcjf4874** [comment]
> 2번 관련으로 생각한 걸 이야기 해보자면, 자신이 원하는 꽃말을 검색 할 때, 결과로 오늘의 꽃도 추가하는 것은 어떨까요? 예를 들어 9월 29일에 A라는 꽃말을 검색하면,
> 
> 1. A라는 꽃말과 관련된 꽃들
> 2. 9월 29일 오늘의 꽃 [9월 29일 : 수세미 /  꽃말 : 여유]
>    이런 식으로 하면 추천을 2개 할 수 있습니다.

좋은 의견입니다!

**Comment by ehdcjf4874** [comment]
의견이 만료되었으므로 닫겠습니다!
