### ISSUE TITLE
프로젝트명 변경

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#8]
프로젝트명을 꽃 추천시스템에서 
꽃말을 통한 꽃 추천 시스템으로 변경했으면 좋겠습니다.
그 이유는 꽃 추천 시스템이라면 제목만 보고 무작위로 추천해준다는 의미일 수도 있고
어떻게 추천해준다는 의미를 부여하고 있지 않으므로
구체화해서 프로젝트명을 바꿨으면 합니다.
의견 올려주세요!
@hdgys45 @gfdsa8

**Comment by hdgys45** [comment]
좋은 의견 같습니다. 우선 저희 어플에서 어떤 추천 기능을 추가 할 지 먼저 정해야할거 같습니다. 이와 관련해서 새로운 이슈를 만들어도 좋을거 같습니다.

**Comment by hdgys45** [comment]
만약 이름을 변경할 것이라면 계획 중인 '상황별 탐색' 기능을 추가할 경우 '꽃말을 통한'이라는 단어가 애매해질 가능성이 있기 때문에  모든 내용을 포괄하는 '꽃 추천'이라는 단어도 충분하다 생각됩니다.
