### ISSUE TITLE
1차 멘토일지

### ISSUE THREAD

**Issue by ehdcjf4874** [hdgys45/Flower-Recommendation-System#9]
[[고찰] 4-1차프로젝트멘토일지.zip](https://github.com/hdgys45/Flower-Recommendation-System/files/7275783/4-1.zip)

1차 멘토일지 초안입니다.
수정할 사항있으면 수정해서 재업로드해주세요!
@hdgys45 @gfdsa8

**Comment by hdgys45** [comment]
별다른 의견 없습니다 수정없이 이대로 제출하면 될거 같습니다.

**Comment by gfdsa8** [comment]
제가 봐도 딱히 수정할 내용이 없는 것 같습니다.
